spring.profiles.active=test
spring.jpa.open-in-view=false

security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}

security.jwt.duration=${JWT_DURATION:86400}

cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

# Porta padrão
server.port=8080

# Configuração do JWT usando chave secreta
spring.security.oauth2.resourceserver.jwt.secret=segredoSuperSegurosegredoSuperSegurosegredoSuperSegurosegredoSuperSeguro

# H2 console (opcional para testes)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource em memória para testes
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
